------------------------------------------------------------------------------
-- This file is reserved for any future times when Blizzard may break things
-- affecting this add-on. Most of the stuff in here is purely patch-specific
-- and temporary and will likely be removed in a following patch.
------------------------------------------------------------------------------
