------------------------------------------------------------------------------
-- This file is reserved for any future times when Blizzard may break things
-- affecting this add-on. Most of the stuff in here is purely patch-specific
-- and temporary and will likely be removed in a following patch.
------------------------------------------------------------------------------



------------------------------------------------------------------------------
-- This is simply a function copied from "Ashel-Antonidas" on the WoW forum.
-- All it does is hide the forbidden function pop-up generated by the new
-- parental controls call. This was an obvious blunder by Blizzard, and they
-- really should fix it - however that is not within the scope of this add-on.
-- Since this add-on is affected by this change, however, this code is
-- necessary, at least on a temporary basis, until the problem is fixed. This
-- will "fix" other add-ons as well.
------------------------------------------------------------------------------

UIParent:HookScript("OnEvent", function(s, e, a1, a2)
	if e:find("ACTION_FORBIDDEN") and ((a1 or "")..(a2 or "")):find("IsDisabledByParentalControls") then
		StaticPopup_Hide(e)
	end;
end)
